version: '3.3'
services:
  mfm:
    build: .
    image: mfm2mqtt:latest
    container_name: mfm2mqtt
    restart: unless-stopped
    user: "0"
  #  environment:  ##aktuell im skript direkt konfiguriert
    # For MQTT Broker:
  #  - MQTT_TOPIC=mfm
  #  - MQTT_HOST=192.168.177.100
  #  - MQTT_PORT=1883
  #  - MQTT_CLIENT_ID=""
  #  - MQTT_KEEPALIVE=60
  #  - MQTT_WILL=None
  #  - MQTT_AUTH=None
    devices:
    # mapping of host HW-serial Interface to docker container 
    #- "/dev/ttyAMA0:/dev/ttyAMA0"
    - "/dev/ttyS0:/dev/ttyS0"